<?php

$allowedFileTypes="['jpg', 'JPG',
                    'jpeg', 'JPEG',
                    'png', 'PNG',
                    'gif', 'GIF',
                    'prt', 'PRT',
                    'sld', 'SLD',
                    'stl', 'STL',
                    'scad', 'SCAD',
                    'asy', 'ASY',
                    'assy', 'ASSY',
                    'asm', 'ASM',
                    'txt', 'TXT',
                    'py', 'PY',
                    'dfx', 'DFX',
                    'rtf', 'RTF',
                    'ods', 'ODS',
                    'odx', 'ODX',
                    'ppt', 'PPT',
                    'pptx', 'PPTX',
                    'doc', 'DOC',
                    'docx', 'DOCX',
                    'xls', 'XLS',
                    'xlsm', 'XLSM',
                    'xlsx', 'XLSX'
                    ]";

?>